name: Hello World

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello Praveen"

      - name: checkout Repo
        uses: actions/checkout@v5

      - name: run file
        run: ls -la
